/**
 * tabPanel
 */
xdescribe("tabPanel.directive", function () {

  // Declare variables.
  var el, scope, controller, template;

  // Load the module.
  beforeEach( angular.mock.module('mnApp') );
  beforeEach( angular.mock.module('tabPanelComponents') );

  // Templates generated by ngHtml2JsPreprocessor.
  beforeEach( angular.mock.module('templateModule') );

  // Mock backend.
  beforeEach( angular.mock.inject(function($httpBackend) {
    $httpBackend
    .whenGET('app/components/tabPanel/tabPanel.template.html')
    .respond("200");
  }));

  // Compile the directive.
  beforeEach( angular.mock.inject(function(_$compile_, _$rootScope_) {
    el       = angular.element('<tab-panel></tab-panel>');
    template = _$compile_(el)(_$rootScope_.$new());
    _$rootScope_.$digest();
    console.log('Isolated scope:', el.isolateScope());
    controller = el.controller();
    scope      = el.isolateScope() || el.scope();
  }));


  /**
   * TODO
   * tabs
   */
  xdescribe('tabs', function() {

    // Sanity check.
    it("scope should be defined", function() {
      expect(scope).toBeDefined()
    })

    // it("template should be defined", function() {
    //   expect(template).toBeDefined()
    // })

    // it("controller should be defined", function() {
    //   expect(controller).toBeDefined()
    // })

    // it('should set a correct title when the about tab is clicked', function() {
    //   //scope.setTab(1);
    //   console.log(scope.setTab);
    //   expect(scope.$parent.title).not.toBe('Masatoshi Nishiguchi');
    // });

  }); // end describe

});
